### ISSUE TITLE
Webstorm 2021.2 issue

### ISSUE THREAD

**Issue by d0whc3r** [jsbeckr/tailwind-idea#7]
```java
java.lang.NullPointerException
	at com.github.jsbeckr.tailwindidea.TailwindAppStarter.copyFromJar(TailwindAppStarter.kt:39)
	at com.github.jsbeckr.tailwindidea.TailwindAppStarter.extractJSFiles(TailwindAppStarter.kt:32)
	at com.github.jsbeckr.tailwindidea.TailwindAppStarter.componentsInitialized(TailwindAppStarter.kt:14)
	at com.intellij.idea.ApplicationLoader$callAppInitialized$1$1.run(ApplicationLoader.kt:376)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by d0whc3r** [comment]
WebStorm 2021.2
Build #WS-212.4746.80, built on July 23, 2021

**Comment by jsbeckr** [comment]
This plugin should not be used with newer IntelliJ versions. Please use the official tailwind plugin from jetbrains: https://plugins.jetbrains.com/plugin/15321-tailwind-css
